# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], max_length=50)),
                ('ticket_type', models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High')], max_length=50)),
                ('message', models.TextField(max_length=9999)),
            ],
        ),
    ]
