"""
Django settings for ticketing_system project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p*0s75ce$lmdd_=%3vr!%m+=19=_7)(&m7yfiqxyc-5k%(%9j#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['byrd-ticketing-system.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clients',
    'bootstrap3'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ticketing_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'ticketing_system/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ticketing_system.wsgi.application'


#This helps on not making mistakes when testing on database. Specifically, to not make changes accidentally in production database.
#To make this working, on the server it has to be added "CUR_DOMAIN" environment variable

try:
    CUR_DOMAIN = os.environ.get('CUR_DOMAIN')
except:
    CUR_DOMAIN = 'localhost'

if CUR_DOMAIN == '' or CUR_DOMAIN is None:
    CUR_DOMAIN ='localhost'


DATABASES_LIST = {
    'ticketing_system': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd5cbq7kqejs8j5',
        'USER': 'gvlcevhwivokdy',
        'PASSWORD': 'b3485ad2b0b97032a38d6cfac0c3928edc2c6e1bdf788450b350820af5427fbc',
        'HOST': 'ec2-184-73-189-190.compute-1.amazonaws.com',
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': None,
        }
    },
    'localhost': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ticketingdb',
        'USER': 'ticketing_admin',
        'PASSWORD': 'ts_admin2017',
        'HOST': 'localhost',
        'PORT': '',
    }

}

DATABASES = {'default': DATABASES_LIST[CUR_DOMAIN]}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = ('%m/%d/%Y')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = 'static' # Important for Heroku
STATIC_URL = '/static/'

# Static files configuration
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "ticketing_system/static"),
)

# Mailing configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587

EMAIL_HOST_USER = 'app67069926@heroku.com'
EMAIL_HOST_PASSWORD = 'fu1vmhoq1022'

DEFAULT_FROM_EMAIL = 'Byrd <noreply@byrd.com>'
